# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: blog.jeonghwan.net
title: 김정환 블로그
description: '#web #backend #angularjs #nodejs #fullstack'
url: http://blog.jeonghwan.net
email: ej88ej@gmail.com
twitter_username: JeonghwanKim4
github_username:  jeonghwan-kim
facebook_username: jeonghwan.kim1
linkedin_username: jeonghwan-kim-07706488

# Handling Reading
#exclude: ['node_modules', '_posts/2014', '_posts/2015'] # Remove comment at local eevelopment mode
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Plugins
gems:
  - jekyll-paginate

# Pagination
paginate: 10

